DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS queries;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    token TEXT NOT NULL
);

CREATE TABLE queries (
    id SERIAL PRIMARY KEY,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    full_name TEXT NOT NULL,
    miles FLOAT NOT NULL,
    mpg FLOAT NOT NULL,
    results TEXT NOT NULL
);
